### ISSUE TITLE
kodi

### ISSUE THREAD

**Issue by carminero1** [NeverWise/plugin.video.skytg24#3]
Ciao, uso Kodi 14.0 su Raspberry.
Ho provato ad aggiungere la riga di codice sul default.py come indicato ma nulla di fatto.
Il fatto è che disabilitando laccellerazione hardware , allora il plugin funziona anche senza aggiungere la riga di codice ma la cpu schizza al 100%.
Ti sarei grato se hai qualche altra soluzione

**Comment by NeverWise** [comment]
Non so cosa risponderti, ho fatto molti test ma aggiungere codice sembra non abbia mai portato benefici.
Io non ho un raspberry e sui dispositivi che uso va, mi vien da pensare che sia un problema di raspberry anche perchè io gli do l'indirizzo dello stream e di solito fa tutto lui.
