### ISSUE TITLE
Doesn't work on KODI 17

### ISSUE THREAD

**Issue by I8NHJ** [NeverWise/plugin.video.skytg24#4]
This is the error I'm getting after installing V17:

04:18:28 T:6316   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'PLAYER_CORE_MPLAYER'
                                            Traceback (most recent call last):
                                              File "C:\Users\Anybody\AppData\Roaming\Kodi\addons\plugin.video.skytg24\default.py", line 7, in <module>
                                                xbmc.Player(xbmc.PLAYER_CORE_MPLAYER).play('rtmp://cp49989.live.edgefcs.net:1935/live/streamRM1@2564 live=true', li)
                                            AttributeError: 'module' object has no attribute 'PLAYER_CORE_MPLAYER'
                                            -->End of Python script error report<--

Thank you for your support.
Max

**Comment by NeverWise** [comment]
This bug has been fixed in the new updated version.
You can find the newer version on my repository at this url: https://github.com/NeverWise/repository.neverwise-storage/raw/master/addons/repository.neverwise/repository.neverwise-1.0.0.zip

**Comment by disimone** [comment]
Hi, I just installed version 1.0.3 on kodi 17.1, and it is not working. This is the error I get

```
21:33:04.288 T:140294094149376   ERROR: GetDirectory - Error getting
21:33:04.424 T:140293398181632   ERROR: Previous line repeats 6 times.
21:33:04.424 T:140293398181632   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'createListItem'
                                            Traceback (most recent call last):
                                              File "/home/disimone/.kodi/addons/plugin.video.skytg24/default.py", line 15, in <module>
                                                st24 = SkyTg24()
                                              File "/home/disimone/.kodi/addons/plugin.video.skytg24/default.py", line 9, in __init__
                                                li = nw.createListItem(nw.addonName, thumbnailImage = '{0}/icon.png'.format(os.path.dirname(os.path.abspath(__file__))), streamtype = 'video', infolabels = { 'title' : nw.addonName })
                                            AttributeError: 'module' object has no attribute 'createListItem'
                                            -->End of Python script error report<--

```

Version 1.0.2, which is installed by kodi by default, does not work either.

Am I doing something wrong?

Andrea.

**Comment by NeverWise** [comment]
It's strange, but It seems that you haven't updated the package script.module.neverwise at the version 1.0.8.
Can you check please?
