### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by ncdotcom** [NeverWise/plugin.video.skytg24#5]
Since around 20 days there's a problem and the plugin doesn't work. It started the day that I changed DNS to the google ones (8.8.8.8 and 8.8.4.4):

11:29:45.043 T:3052   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
11:29:45.326 T:2516   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name Util
                                            Traceback (most recent call last):
                                              File "C:\Users\NC\AppData\Roaming\Kodi\addons\plugin.video.skytg24\default.py", line 3, in <module>
                                                from neverwise import Util
                                            ImportError: cannot import name Util
                                            -->End of Python script error report<--
11:29:45.367 T:3052   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.skytg24/
11:29:45.367 T:3052   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.skytg24/) failed
11:29:57.5

**Comment by NeverWise** [comment]
It seems that you haven't updated the package script.module.neverwise at the version 1.0.8.
Can you check please?
